src/domain/App.Frontend/Controllers/CartController.cs
using Newtonsoft.Json;
using App.Frontend.Models;
using App.Frontend.Services;
using Microsoft.AspNetCore.Mvc;
using System.IdentityModel.Tokens.Jwt;
using App.Frontend.Utility;

namespace App.Frontend.Controllers
{
    public class CartController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly ICartService _cartService;

        public CartController(ICartService cartService, IOrderService orderService)
        {
            _cartService = cartService;
            _orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View(await LoadCart());
            }
            else
            {
                return RedirectToAction("Login", "Authentication");
            }
        }

        public async Task<IActionResult> Checkout()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View(await LoadCart());
            }
            else
            {
                return RedirectToAction("Login", "Authentication");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(Cart cartInfomation)
        {
            var cart = await LoadCart();
            cart.CartHeader.Phone = cartInfomation.CartHeader.Phone;

            var response = await _orderService.CreateOrder(cart);
            if (response.IsSuccess && response != null)
            {
                var orderHeader = JsonConvert.DeserializeObject<OrderHeader>(Convert.ToString(response.Result));

                //get stripe session and redirect to stripe to place order
                var domain = Request.Scheme + "://" + Request.Host.Value + "/";
                StripeRequest stripeRequest = new()
                {
                    ApprovedUrl = domain + "cart/Confirmation/orderId=" + orderHeader?.Id,
                    CancelUrl = domain + "cart/Checkout",
                    OrderHeader = orderHeader,
                };

                var stripeResponse = await _orderService.CreateStripeSession(stripeRequest);
                if (stripeResponse != null)
                {
                    var stripeResponseResult = JsonConvert.DeserializeObject<StripeRequest>(Convert.ToString(stripeResponse.Result));
                    Response.Headers?.Add("Location", stripeResponseResult.StripeSessionUrl);
                }
                return new StatusCodeResult(303);
            }
            return View(cart);
        }

        public async Task<IActionResult> Confirmation(string orderId)
        {
            if (User.Identity.IsAuthenticated)
            {
                Response response = await _orderService.ValidateStripeSession(orderId);
                if (response.IsSuccess && response != null)
                {
                    return View(orderId);
                }
                return View(orderId);
            }
            else
            {
                return RedirectToAction("Login", "Authentication");
            }
        }

        public async Task<IActionResult> Delete(string cartDetailsId)
        {
            Response? response = await _cartService.DeleteAsync(cartDetailsId);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = response?.Message;
                HttpContext.Session.SetString(StaticDetail.SessionCart, JsonConvert.SerializeObject(response.Result));
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return RedirectToAction(nameof(Index));
        }

        private async Task<Cart> LoadCart()
        {
            //var userId = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
            //Hiệu suất tốt hơn: FindFirst() dừng ngay khi tìm thấy kết quả, thay vì duyệt qua tất cả các claim.
            var userId = User.FindFirst(JwtRegisteredClaimNames.Sub)?.Value;
            var userEmail = User.FindFirst(JwtRegisteredClaimNames.Email)?.Value;
            var userName = User.FindFirst(JwtRegisteredClaimNames.Name)?.Value;


            Response? response = await _cartService.GetAsync(userId);
            if (response != null && response.IsSuccess)
            {
                Cart cart = JsonConvert.DeserializeObject<Cart>(Convert.ToString(response.Result));
                cart.CartHeader.Name = userName;
                cart.CartHeader.Email = userEmail;

                HttpContext.Session.SetString(StaticDetail.SessionCart, JsonConvert.SerializeObject(response.Result));
                return cart;
            }
            return new Cart();
        }
    }
}

src/domain/App.Frontend/Controllers/OrderController.cs
using Newtonsoft.Json;
using App.Frontend.Models;
using App.Frontend.Services;
using App.Frontend.Utility;
using Microsoft.AspNetCore.Mvc;
using System.IdentityModel.Tokens.Jwt;

namespace App.Frontend.Controllers;
public class OrderController : Controller
{
    private readonly IOrderService _orderService;

    public OrderController(IOrderService orderService)
    {
        _orderService = orderService;
    }
    public IActionResult Index()
    {
        if (User.Identity.IsAuthenticated)
        {
            return View();
        }
        else
        {
            return RedirectToAction("Login", "Authentication");
        }
    }

    [HttpGet]
    public async Task<IActionResult> Details(string orderId)
    {
        if (User.Identity.IsAuthenticated)
        {
            OrderHeader orderHeader = new OrderHeader();
            var userId = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;

            Response response = await _orderService.Get(orderId);
            if (response.IsSuccess && response != null)
            {
                orderHeader = JsonConvert.DeserializeObject<OrderHeader>(Convert.ToString(response.Result));
            }
            if (!User.IsInRole(StaticDetail.RoleAdmin) && userId != orderHeader.UserId)
            {
                return NotFound();
            }
            return View(orderHeader);
        }
        else
        {
            return RedirectToAction("Login", "Authentication");
        }
    }

    [HttpPost("OrderReadyForPickup")]
    public async Task<IActionResult> OrderReadyForPickup(string orderId)
    {
        return View();
    }

    [HttpPost("CompleteOrder")]
    public async Task<IActionResult> CompleteOrder(string orderId)
    {
        return View();
    }

    [HttpPost("CancelOrder")]
    public async Task<IActionResult> CancelOrder(string orderId)
    {
        return View();
    }

    [HttpGet]
    public IActionResult Get(string status)
    {
        if (User.Identity.IsAuthenticated)
        {
            IEnumerable<OrderHeader> list;
            string userId = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
            Response response = _orderService.GetAllOrder(userId).GetAwaiter().GetResult();
            if (response.IsSuccess && response != null)
            {
                list = JsonConvert.DeserializeObject<List<OrderHeader>>(Convert.ToString(response.Result));
                switch (status)
                {
                    case "approved":
                        list = list.Where(u => u.Status == StaticDetail.Status_Approved);
                        break;
                    case "readyforpickup":
                        list = list.Where(u => u.Status == StaticDetail.Status_ReadyForPickup);
                        break;
                    case "cancelled":
                        list = list.Where(u => u.Status == StaticDetail.Status_Cancelled);
                        break;
                    default:
                        break;
                }
            }
            else
            {
                list = new List<OrderHeader>();
            }
            return Json(new { data = list.OrderByDescending(u => u.Id) });
        }
        else
        {
            return RedirectToAction("Login", "Authentication");
        }
    }
}

src/domain/App.Frontend/Views/Shared/_Layout.cshtml
@using App.Frontend.Utility
<!DOCTYPE html>
<html lang="en">

@{
    var externalUrl = "";
}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link asp-append-version="true" rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    <link asp-append-version="true" rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link asp-append-version="true" rel="stylesheet" href="~/css/Layout.css" />
    <link asp-append-version="true" rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    <link asp-append-version="true" rel="stylesheet"
        href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    <link asp-append-version="true" rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">

</head>

<body>
    <nav class="sidebar">
        <div class="sidebar-top-wrapper">
            <div class="sidebar-top">
                <a asp-controller="Home" asp-action="Index" class="logo__wrapper">
                    <img src="~/lib/image/logo.png" alt="Logo" class="logo-small">
                    <span class="hide company-name">
                        Apple Store
                    </span>
                </a>
            </div>
            <button class="expand-btn" type="button" title="Close Sidebar" id="close sidebar">
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M6.00979 2.72L10.3565 7.06667C10.8698 7.58 10.8698 8.42 10.3565 8.93333L6.00979 13.28"
                        stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
            </button>
        </div>
        <div class="divider"></div>
        <h2>Customer</h2>
        <div class="divider"></div>
        <div class="sidebar-links-wrapper">
            <div class="sidebar-links">
                <h2>Product</h2>
                <div class="divider"></div>
                <ul>
                    <li>
                        <a asp-controller="Home" asp-action="Index" title="products">
                            <svg version="1.1" id="Icons" xmlns="http://www.w3.org/2000/svg"
                                xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 26 30"
                                fill="none" xml:space="preserve" fill="#000000">
                                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                <g id="SVGRepo_iconCarrier">
                                    <path class="st0" d="M15,3v1.3C15,5.2,14.2,6,13.3,6h-2.6C9.8,6,9,5.2,9,4.3V3">
                                    </path>
                                    <path class="st0"
                                        d="M19,7V5c0-1.1-0.9-2-2-2H7C5.9,3,5,3.9,5,5v22c0,1.1,0.9,2,2,2h10c1.1,0,2-0.9,2-2v-2">
                                    </path>
                                    <circle class="st0" cx="20" cy="15" r="4"></circle>
                                    <path class="st0"
                                        d="M24.2,16.4l2.1,2.1c0.8,0.8,0.8,2.1,0,2.8l0,0c-0.8,0.8-2.1,0.8-2.8,0l-2.1-2.1">
                                    </path>
                                    <line class="st0" x1="9" y1="25" x2="15" y2="25"></line>
                                </g>
                            </svg>
                            <span class="link hide">Products</span>
                        </a>
                    </li>
                </ul>
                <h2>Cart</h2>
                <div class="divider"></div>
                <ul>
                    <li>
                        <a asp-controller="Cart" asp-action="Index" title="products">
                            <svg version="1.1" id="Icons" xmlns="http://www.w3.org/2000/svg"
                                xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 26 30"
                                fill="none" xml:space="preserve" fill="#000000">
                                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                <g id="SVGRepo_iconCarrier">
                                    <path class="st0" d="M15,3v1.3C15,5.2,14.2,6,13.3,6h-2.6C9.8,6,9,5.2,9,4.3V3">
                                    </path>
                                    <path class="st0"
                                        d="M19,7V5c0-1.1-0.9-2-2-2H7C5.9,3,5,3.9,5,5v22c0,1.1,0.9,2,2,2h10c1.1,0,2-0.9,2-2v-2">
                                    </path>
                                    <circle class="st0" cx="20" cy="15" r="4"></circle>
                                    <path class="st0"
                                        d="M24.2,16.4l2.1,2.1c0.8,0.8,0.8,2.1,0,2.8l0,0c-0.8,0.8-2.1,0.8-2.8,0l-2.1-2.1">
                                    </path>
                                    <line class="st0" x1="9" y1="25" x2="15" y2="25"></line>
                                </g>
                            </svg>
                            @* <span class="link hide">Cart @await Component.InvokeAsync("ShoppingCart")</span> *@
                            <span class="link hide">Cart</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="divider"></div>
        @if (User.IsInRole(StaticDetail.RoleAdmin))
        {
            <h2>Admin</h2>
            <div class="divider"></div>
            <div class="sidebar-links-wrapper">
                <div class="sidebar-links">
                    <h2>Product</h2>
                    <div class="divider"></div>
                    <ul>
                        <li>
                            <a asp-controller="Product" asp-action="Index" title="products">
                                <svg version="1.1" id="Icons" xmlns="http://www.w3.org/2000/svg"
                                    xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 26 30"
                                    fill="none" xml:space="preserve" fill="#000000">
                                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                    <g id="SVGRepo_iconCarrier">
                                        <path class="st0" d="M15,3v1.3C15,5.2,14.2,6,13.3,6h-2.6C9.8,6,9,5.2,9,4.3V3">
                                        </path>
                                        <path class="st0"
                                            d="M19,7V5c0-1.1-0.9-2-2-2H7C5.9,3,5,3.9,5,5v22c0,1.1,0.9,2,2,2h10c1.1,0,2-0.9,2-2v-2">
                                        </path>
                                        <circle class="st0" cx="20" cy="15" r="4"></circle>
                                        <path class="st0"
                                            d="M24.2,16.4l2.1,2.1c0.8,0.8,0.8,2.1,0,2.8l0,0c-0.8,0.8-2.1,0.8-2.8,0l-2.1-2.1">
                                        </path>
                                        <line class="st0" x1="9" y1="25" x2="15" y2="25"></line>
                                    </g>
                                </svg>
                                <span class="link hide">Products</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        }
        <div class="divider"></div>
        <h2>Order</h2>
        <div class="divider"></div>
        <div class="sidebar-links-wrapper">
            <div class="sidebar-links">
                <div class="divider"></div>
                <ul>
                    <li>
                        <a asp-controller="Order" asp-action="Index" title="orders">
                            <svg version="1.1" id="Icons" xmlns="http://www.w3.org/2000/svg"
                                xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 26 30"
                                fill="none" xml:space="preserve" fill="#000000">
                                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                <g id="SVGRepo_iconCarrier">
                                    <path class="st0" d="M15,3v1.3C15,5.2,14.2,6,13.3,6h-2.6C9.8,6,9,5.2,9,4.3V3">
                                    </path>
                                    <path class="st0"
                                        d="M19,7V5c0-1.1-0.9-2-2-2H7C5.9,3,5,3.9,5,5v22c0,1.1,0.9,2,2,2h10c1.1,0,2-0.9,2-2v-2">
                                    </path>
                                    <circle class="st0" cx="20" cy="15" r="4"></circle>
                                    <path class="st0"
                                        d="M24.2,16.4l2.1,2.1c0.8,0.8,0.8,2.1,0,2.8l0,0c-0.8,0.8-2.1,0.8-2.8,0l-2.1-2.1">
                                    </path>
                                    <line class="st0" x1="9" y1="25" x2="15" y2="25"></line>
                                </g>
                            </svg>

                            <span class="link hide">Order History</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="divider"></div>
        </div>
        @if (User.IsInRole(StaticDetail.RoleAdmin))
        {
            <a href="#" onclick="javascript:window.open('@externalUrl', '_blank');" disabled>
                <button class="btn-primary btn form-control">Admin Central</button>
            </a>
        }
        <div class="divider"></div>
        <!-- Login Partial Section -->
        @await Html.PartialAsync("_LoginPartial")
    </nav>
    <main id="main">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications" />
        </main>
        <footer class="border-top footer text-muted">
            <div class="container">
                <small>&copy;2024 Ecommerce-MVC-ASP.NET-C# | Email: levanhiep409159@gmail.com |<a
                        href="https://github.com/leh23211213/Demo-Microservice-Based-.NET-Applications">Git
                        Repository</a></small>
            </div>
        </footer>
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

src/domain/App.Frontend/Views/Shared/coverPage.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/CoverPage.css" asp-append-version="true">
    <style>
        .header {
            padding-bottom: 0;
            min-height: 5rem;
            flex-direction: row;
            justify-content: space-between;
            position: relative;
            padding-top: 0;
        }
    </style>
</head>

<body>
    <!-- Header  -->
    <header id="header">
        <div class="header container">
            <nav class="nav-list">
                <ul class="nav-links">
                    <li><a href="#" class="nav-link">Home</a></li>
                    <li><a href="#features" class="nav-link">Features</a></li>
                    <li><a href="#footer" class="nav-link">Contact</a></li>
                </ul>
                <ul class="nav-links extra">
                    <li>
                        <a asp-controller="Authentication" asp-action="Login" class="nav-link">
                            <button class="cta">
                                <span>Get Started</span>
                                <svg width="15px" height="10px" viewBox="0 0 13 10">
                                    <path d="M1,5 L11,5"></path>
                                    <polyline points="8 1 12 5 8 9"></polyline>
                                </svg>
                            </button>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <!-- End Header  -->

    <!-- background -->
    <section id="background">
        <div class="background container">
            <article class="article">
            </article>
        </div>
    </section>
    <!-- End background -->

    <!-- features -->
    <section id="features">
        <div class="features container">

            <div class="intro">
                <h1 class="primary-title feature">Introduce about features</h1>
            </div>

            <div class="collection">
                <article class="article">
                    <div class="feature-img">
                        <img src="~/lib/image/dashboard.png" class="image">
                    </div>
                    <div class="feature-details">
                        <h2 class="secondary-title">Dashboard</h2>
                        <p>Easily navigate through all the functionalities of the application with our intuitive
                            dashboard.
                        </p>
                    </div>
                </article>

                <article class="article">
                    <div class="feature-img">
                        <img src="~/lib/image/showandsearchproduct.png" class="image" alt="">
                    </div>
                    <div class="feature-details">
                        <h2 class="secondary-title">Cart</h2>
                        <p>Save your favorite items for later or proceed directly to purchase with our seamless cart
                            feature.</p>
                    </div>
                </article>
                <article class="article">
                    <div class="feature-img">
                        <img src="~/lib/image/Cart.png" class="image" alt="">
                    </div>
                    <div class="feature-details">
                        <h2 class="secondary-title">Product Viewing and Search</h2>
                        <p> explore a wide range of products with our comprehensive viewing and search capabilities.
                        </p>
                    </div>
                </article>
            </div>
        </div>
    </section>
    <!-- End features -->


    <!-- Footer  //TODO : footer form midde-->
    <footer id="footer">
        <div class="footer container">

            <p class="copyright">
            <h1>Thank For Visited</h1>
            </p>

            <div class="link-columns">
                <section>
                    <h3>Reference Source</h3>
                    <ul>
                        <li>
                            <a href="https://www.microsoft.com/en-us/sql-server/sql-server-downloads"
                                title="Features">Database</a>
                        </li>
                    </ul>
                </section>
            </div>

            <div class="social-wrapper">
                <div class="social-links">
                    <h3 class="secondary-title" id="contact-us">Contact us</h3>
                    <ul class="contact-links">
                        <li><a href="https://www.linkedin.com/in/le-hiep-1809b4184/" class="icon nav-link">
                                <svg xmlns="http://www.w3.org/2000/svg" class="linkedin" height="1.6em"
                                    viewBox="0 0 448 512">
                                    <path
                                        d="M100.3 448H7.4V148.9h92.9zM53.8 108.1C24.1 108.1 0 83.5 0 53.8a53.8 53.8 0 0 1 107.6 0c0 29.7-24.1 54.3-53.8 54.3zM447.9 448h-92.7V302.4c0-34.7-.7-79.2-48.3-79.2-48.3 0-55.7 37.7-55.7 76.7V448h-92.8V148.9h89.1v40.8h1.3c12.4-23.5 42.7-48.3 87.9-48.3 94 0 111.3 61.9 111.3 142.3V448z">
                                    </path>
                                </svg>
                            </a></li>
                        <li><a href="https://github.com/leh23211213" class="icon nav-link">
                                <svg class="github" height="30px" width="30px" viewBox="0 0 30 30"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M15,3C8.373,3,3,8.373,3,15c0,5.623,3.872,10.328,9.092,11.63C12.036,26.468,12,26.28,12,26.047v-2.051 c-0.487,0-1.303,0-1.508,0c-0.821,0-1.551-0.353-1.905-1.009c-0.393-0.729-0.461-1.844-1.435-2.526 c-0.289-0.227-0.069-0.486,0.264-0.451c0.615,0.174,1.125,0.596,1.605,1.222c0.478,0.627,0.703,0.769,1.596,0.769 c0.433,0,1.081-0.025,1.691-0.121c0.328-0.833,0.895-1.6,1.588-1.962c-3.996-0.411-5.903-2.399-5.903-5.098 c0-1.162,0.495-2.286,1.336-3.233C9.053,10.647,8.706,8.73,9.435,8c1.798,0,2.885,1.166,3.146,1.481C13.477,9.174,14.461,9,15.495,9 c1.036,0,2.024,0.174,2.922,0.483C18.675,9.17,19.763,8,21.565,8c0.732,0.731,0.381,2.656,0.102,3.594 c0.836,0.945,1.328,2.066,1.328,3.226c0,2.697-1.904,4.684-5.894,5.097C18.199,20.49,19,22.1,19,23.313v2.734 c0,0.104-0.023,0.179-0.035,0.268C23.641,24.676,27,20.236,27,15C27,8.373,21.627,3,15,3z">
                                    </path>
                                </svg>
                            </a></li>
                    </ul>
                </div>
            </div>

            <!-- bottom part section -->
            <div class="footer-bottom">
                <div class="footer-bottom-wrapper">
                    <small>&copy;2024 Ecommerce-MVC-ASP.NET-C# | Email: levanhiep409159@gmail.com |<a
                            href="https://github.com/leh23211213/Demo-Microservice-Based-.NET-Applications">Git
                            Repository</a></small>
                </div>
            </div>

        </div>
    </footer>
    <!--End Footer-->

    <script>
        const header = document.querySelector('#header');
        document.addEventListener('scroll', () => {
            var scroll_position = window.scrollY;
            if (scroll_position > 190) {
                header.style.backgroundColor = 'black';
            } else {
                header.style.backgroundColor = 'transparent';
            }
        });
    </script>
</body>